server:
  port: 9081

spring:
  application:
      name: msvc-security
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=SERVICIOSARIANA;trustServerCertificate=true
    username: codel
    password: 123

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ServiciosAriana2024_JWT_Secret_Key_For_Microservices_Architecture_SuperSecure!
  expiration: 1800000 # 30 minutos
  refresh-expiration: 604800000 # 7 d√≠as

security:
  password:
    encoder:
      strength: 12 # Para BCrypt